--- #YAML:1.0
name:                   WWW-Scraper-ISBN-GoogleBooks_Driver
version:                0.05
abstract:               Search driver for Google Books online book catalog
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  JSON:                         0
  Test::More:                   0.45
  WWW::Mechanize:               1.60
  WWW::Scraper::ISBN:           0.25
  WWW::Scraper::ISBN::Driver:   0.18
recommends:
  Test::More:                   0.70
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
  Test::CPAN::Meta:             0.13
  Test::CPAN::Meta::JSON:       0.10
build_requires:
  Test::More:                   0.45

provides:
  WWW::Scraper::ISBN::GoogleBooks_Driver:
    file:     lib/WWW/Scraper/ISBN/GoogleBooks_Driver.pm
    version:  0.05
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
